"""Adaptive regression tree package."""

from .builder import (
    RegressionTreeBuilder,
    TreeBuildResult,
)
from .domain import BoxDomain, PolytopeRegion, split_region
from .metrics import (
    max_pointwise_relative_error,
    mean_squared_error,
    median_pointwise_relative_error,
    pointwise_relative_error,
    relative_l2_error,
    sum_squared_error,
)
from .models import (
    AffineRidgeModel,
    KernelRidgeModel,
    PolynomialRidgeModel,
    RegressionModel,
    WeightedRegressionModel,
    model_effective_dimension,
    polynomial_feature_count,
    scaled_ridge_from_gram,
    solve_weighted_ridge,
)
from .objectives import (
    SoftObjectiveResult,
    SoftObliqueRidgeObjective,
    sigmoid,
)
from .optimizers import AdaptiveAlpha, LineSearchResult, armijo_backtracking
from .sampling import (
    HitAndRunSampler,
    Sampler,
    UniformBoxSampler,
    autocorrelation_by_lag,
    estimate_thinning_from_chain,
    find_feasible_point,
    infer_box_bounds,
    make_thinning_candidates,
    sample_uniform_box,
)
from .splitters import (
    HingeAffineSplitter,
    SoftObliqueSplitter,
    SplitNotFoundError,
    SplitResult,
    Splitter,
    project_unit_w,
    project_unit_w_gradient,
)
from .temperature import (
    DEFAULT_TEMPERATURE_GRID,
    TemperatureConfig,
    estimate_temperature,
    median_nearest_neighbor_distance,
    median_pairwise_distance,
    pairwise_distances,
    subsample_points,
    temperature_grid,
)
from .tree import LeafNode, RegressionTree, SplitNode

__all__ = [
    "AffineRidgeModel",
    "AdaptiveAlpha",
    "BoxDomain",
    "DEFAULT_TEMPERATURE_GRID",
    "HingeAffineSplitter",
    "HitAndRunSampler",
    "KernelRidgeModel",
    "LeafNode",
    "LineSearchResult",
    "PolytopeRegion",
    "PolynomialRidgeModel",
    "RegressionModel",
    "RegressionTree",
    "RegressionTreeBuilder",
    "Sampler",
    "SoftObjectiveResult",
    "SoftObliqueSplitter",
    "SoftObliqueRidgeObjective",
    "SplitNode",
    "SplitNotFoundError",
    "SplitResult",
    "Splitter",
    "TemperatureConfig",
    "TreeBuildResult",
    "UniformBoxSampler",
    "WeightedRegressionModel",
    "armijo_backtracking",
    "autocorrelation_by_lag",
    "estimate_temperature",
    "estimate_thinning_from_chain",
    "find_feasible_point",
    "infer_box_bounds",
    "make_thinning_candidates",
    "max_pointwise_relative_error",
    "mean_squared_error",
    "median_nearest_neighbor_distance",
    "median_pairwise_distance",
    "median_pointwise_relative_error",
    "model_effective_dimension",
    "pairwise_distances",
    "pointwise_relative_error",
    "polynomial_feature_count",
    "project_unit_w",
    "project_unit_w_gradient",
    "relative_l2_error",
    "sample_uniform_box",
    "scaled_ridge_from_gram",
    "sigmoid",
    "solve_weighted_ridge",
    "split_region",
    "subsample_points",
    "sum_squared_error",
    "temperature_grid",
]
